version: '3.7'
services:
  javbus-tg-bot:
    container_name: javbus-tg-bot
    environment:
      # replace with your bot name and bot token
      - JAVBUS_BOT_NAME=replace-with-your-bot-name
      - JAVBUS_BOT_TOKEN=replace-with-your-bot-token
    volumes:
      - ./javbus-tg-bot.db:/app/javbus-tg-bot.db
      - ./log:/app/log
    image: 'liuzy/javbus-tg-bot'